# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 00预处理.py
# Created on: 2021-10-09 13:28:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 00预处理 <boundary> <Zone_field> <InputShape> <result> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
# -*- coding: utf-8 -*-
import arcpy

envfile = r"D:\Work\doing\CNN_RNN\data\beijing\inputdata\ALT.tif"
prjfile = r"D:\Work\doing\CNN_RNN\data\beijing\origindata\boundary.prj"

arcpy.env.overwriteOutput = 1 # 可覆盖
arcpy.env.workspace = r"D:\Work\doing\CNN_RNN\data\processdata" # 设置工作路径
arcpy.env.outputCoordinateSystem = prjfile
arcpy.env.extent = "MAXOF" # 设置范围
# arcpy.env.extent = arcpy.Extent(454871.698900, 4253992.158900, 624251.698900, 4437472.158900) # "XMin, YMin, XMax, YMax"
arcpy.env.extent = envfile
# arcpy.env.cellSize = 30 # 像元大小
arcpy.env.cellSize = envfile
arcpy.env.snapRaster = envfile

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
# boundary = arcpy.GetParameterAsText(0)
boundary = r"D:\Work\doing\CNN_RNN\data\beijing\origindata\boundary.shp"
Zone_field = "FID"

InputShape = r"D:\Work\doing\CNN_RNN\data\origindata\Road\highWay.shp"

result = r"D:\Work\doing\CNN_RNN\data\beijing\inputdata\HID.tif"

if result == '#' or not result:
    result = "D:\\Work\\doing\\CNN_RNN\\data\\beijing\\processdata\\result" # provide a default value if unspecified

# Local variables:
Parallel_Processing_Factor = "0"
EucDist_shoreli1_tif = ""
Extract_EucDis10_tif = ""
rastercalc = "d:\\Mr.pan\\temporariness\\arcgisdata\\rastercalc"
ZonalSt_boundar1 = ""
Value = ZonalSt_boundar1
Value__2_ = ZonalSt_boundar1
rastercalc_r = "d:\\work\\doing\\cnn_rnn\\data\\beijing\\processdata\\rastercalc_r"
Output_direction_raster = ""
Output_back_direction_raster = ""

# Process: Euclidean Distance
tempEnvironment0 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = Parallel Processing Factor
arcpy.gp.EucDistance_sa(InputShape, EucDist_shoreli1_tif, "", r"D:\Work\doing\CNN_RNN\data\beijing\inputdata\ALT.tif", Output_direction_raster, "PLANAR", "", Output_back_direction_raster)
arcpy.env.parallelProcessingFactor = tempEnvironment0

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa(EucDist_shoreli1_tif, boundary, Extract_EucDis10_tif)

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("Float(\"%Extract_EucDis10.tif%\")", rastercalc)

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(boundary, Zone_field, rastercalc, ZonalSt_boundar1, "DATA", "MIN_MAX")

# Process: Get Field Value (2)
arcpy.GetFieldValue_mb(ZonalSt_boundar1, "MIN", "Double", "0")

# Process: Get Field Value
arcpy.GetFieldValue_mb(ZonalSt_boundar1, "MAX", "Double", "0")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(\"%rastercalc%\"-%Value (2)%) / (%Value%-%Value (2)%)", rastercalc_r)

# Process: Extract by Mask (2)
arcpy.gp.ExtractByMask_sa(rastercalc_r, boundary, result)

